### ISSUE TITLE
Team contact, co-author paper

### ISSUE THREAD

**Issue by n-emmanuelle** [AwAReUU/OpenAwARe#4]
Hi Team,

I have sent you all an email with a request to co-author a paper. I have used your old email addresses, but not sure if those still work. Please email me at my new email if you are interested in co-authoring (and also email me if you are not interested), I can provide more specific details via email. Thanks!

N

**Comment by Mackthis** [comment]
Hi Nina,

I saw the mail, and the deadline is a little short for me, and I do not have time available atm. Also, during the project I have been more at work with testing and debugging, which should not be interesting for your paper.

The original documentation/report should provide enough information, however. That said, most of the current implementation should be replaced or optimized. (Better algorithm, parallelization, etc.) I should consider first drastically improving the performance, desired results, and looks before going further on it. For more advise, see the "Future Development" section of our report.

If you consider further development, I might be interested, either voluntarily as a side project (free-time/vacation) or as a side job (more frequent efforts). Now I have more experience with Computer Vision and Optimization, I am better able to improve things. This said, considering how Unity documents things, it would take some time to work things out. My advice would be, if you want me or others to tackle these, to do one component at a time, unlike this project.

But to get back to the paper: I have to decline. I hope that the others can help you out more. If there are any other questions, please ask!

Goodluck to you,
Sander
